"""Generate a one-page PDF summary from saved experiment artifacts."""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
import pandas as pd


def _project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def generate_one_page_summary(project_root: Path | None = None) -> Path:
    """Build a concise one-page PDF summary."""

    project_root = project_root or _project_root()
    summary_paths = sorted((project_root / "results" / "artifacts").glob("*/*_summary.json"))
    summaries = [json.loads(path.read_text(encoding="utf-8")) for path in summary_paths]
    output_path = project_root / "reports" / "instashap_summary_1page.pdf"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "Objective: reproduce InstaSHAP on Bike Sharing, Covertype, and Adult Income.",
        "Core method: train an additive model with the paper's masked objective so SHAP-like attributions",
        "can be read directly from additive components in one forward pass.",
        "",
        "Available result tables:",
    ]
    for summary in summaries:
        metrics_df = pd.read_csv(project_root / summary["metrics_table"])
        primary_column = "nmse_pct" if summary["task"] == "regression" else "accuracy"
        best_row = metrics_df.sort_values(primary_column, ascending=summary["task"] == "regression").head(1)
        if not best_row.empty:
            row = best_row.iloc[0]
            lines.append(f"- {summary['dataset']}: best {row['model']} {primary_column}={row[primary_column]:.4f}")
    lines.extend(
        [
            "",
            "Artifacts generated by the project:",
            "- Dataset loaders and preprocessing using ucimlrepo",
            "- Black-box, GAM, surrogate, and InstaSHAP implementations",
            "- Metrics tables, plots, PDF report, and notebook scaffold",
        ]
    )

    with PdfPages(output_path) as pdf:
        fig = plt.figure(figsize=(8.27, 11.69))
        fig.text(0.08, 0.95, "InstaSHAP One-Page Summary", fontsize=18, fontweight="bold", va="top")
        y = 0.9
        for line in lines:
            fig.text(0.08, y, line, fontsize=11, va="top")
            y -= 0.035
        pdf.savefig(fig)
        plt.close(fig)
    return output_path


if __name__ == "__main__":
    summary_path = generate_one_page_summary()
    print(summary_path)
